
# Run pipeline on master branch, pull-requests into master, and tags
trigger:
  branches:
    include:
    - master
    - refs/tags/*

pr:
- master

pool:
  vmImage: ubuntu-latest

stages:

- stage: Test
  jobs:
  - job: Test

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
        npm test
      displayName: 'npm test'

- stage: DevDeployment
  displayName: 'Dev Deployment'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn:
  - Test
  jobs:
  - deployment: Deployment
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-templates/deploy.yaml
            parameters:
              environment: 'dev'
              region: 'uks'

- stage: StagDeployment
  displayName: 'Stag Deployment'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  dependsOn:
  - Test
  jobs:
  - deployment: Deployment
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-templates/deploy.yaml
            parameters:
              environment: 'stag'
              region: 'uks'

- stage: ProdDeployment
  displayName: 'Prod Deployment'
  dependsOn:
  - StagDeployment
  - Test
  jobs:
  - deployment: Deployment
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-templates/deploy.yaml
            parameters:
              environment: 'prod'
              region: 'uks'
